import { useState } from 'react'
import { collection, doc, writeBatch } from 'firebase/firestore'

import { db } from './firebase'

// One-time Phase 1a data import (PLAN.md) — not a permanent app screen.
// Markus picks the JSON files generated by migration/*.py (never bundled
// into the public app, never committed — see CODEMAP.md's migration/
// section) straight from his device or Google Drive while signed in, and
// this writes them into his own Firestore via the batched-write API. Every
// document id is a deterministic slug (accounts/categories/tags) or a
// deterministic sequence (tx-2025-00001, b-2026-plan1-...), so re-running
// this on the same files only overwrites with identical data — safe to
// repeat if a file was missed the first time.
const FILE_PATTERNS = [
  { re: /^accounts\.json$/i, collectionName: 'accounts' },
  { re: /^categories\.json$/i, collectionName: 'categories' },
  { re: /^tags-allocation\.json$/i, collectionName: 'tags' },
  { re: /^tags-breakdown-\d{4}\.json$/i, collectionName: 'tags' },
  { re: /^jahresabschluss\.json$/i, collectionName: 'transactions' },
  { re: /^transactions-\d{4}\.json$/i, collectionName: 'transactions' },
  { re: /^budgets-\d{4}\.json$/i, collectionName: 'budgets' },
]
// Fixed write order — cosmetic only, Firestore has no cross-collection
// constraints, but it makes the progress list read top-to-bottom sensibly.
const COLLECTION_ORDER = ['accounts', 'categories', 'tags', 'transactions', 'budgets']
const CHUNK_SIZE = 400 // Firestore's batch limit is 500 writes; leave headroom

function classify(filename) {
  const match = FILE_PATTERNS.find((p) => p.re.test(filename))
  return match?.collectionName ?? null
}

async function readJsonFile(file) {
  const text = await file.text()
  const data = JSON.parse(text)
  if (!Array.isArray(data)) {
    throw new Error('Erwartet eine Liste von Dokumenten (JSON-Array).')
  }
  for (const item of data) {
    if (!item || typeof item.id !== 'string') {
      throw new Error('Jedes Dokument braucht ein id-Feld.')
    }
  }
  return data
}

async function writeCollection(collectionName, docsById, onProgress) {
  const entries = Object.entries(docsById)
  for (let i = 0; i < entries.length; i += CHUNK_SIZE) {
    const slice = entries.slice(i, i + CHUNK_SIZE)
    const batch = writeBatch(db)
    for (const [id, data] of slice) {
      batch.set(doc(collection(db, collectionName), id), data)
    }
    await batch.commit()
    onProgress(Math.min(i + CHUNK_SIZE, entries.length))
  }
}

export default function ImportScreen() {
  // { [filename]: { collectionName, count, error } }
  const [files, setFiles] = useState({})
  const [running, setRunning] = useState(false)
  const [progress, setProgress] = useState({}) // { [collectionName]: { done, total } }
  const [done, setDone] = useState(false)
  const [runError, setRunError] = useState(null)

  async function handleFilesSelected(fileList) {
    setDone(false)
    setRunError(null)
    const next = {}
    for (const file of Array.from(fileList)) {
      const collectionName = classify(file.name)
      if (!collectionName) {
        next[file.name] = { collectionName: null, count: 0, error: 'Unbekannter Dateiname — wird ignoriert.' }
        continue
      }
      try {
        const docs = await readJsonFile(file)
        next[file.name] = { collectionName, count: docs.length, docs, error: null }
      } catch (err) {
        next[file.name] = { collectionName, count: 0, error: err.message }
      }
    }
    setFiles((prev) => ({ ...prev, ...next }))
  }

  const usableFiles = Object.entries(files).filter(([, f]) => f.collectionName && !f.error)
  const hasUsableFiles = usableFiles.length > 0

  async function handleImport() {
    setRunning(true)
    setRunError(null)
    setDone(false)
    setProgress({})
    try {
      // Merge same-collection files (e.g. two years of transactions) and
      // dedupe by id — the migration scripts guarantee identical content
      // for any id that appears in more than one file.
      const byCollection = {}
      for (const [, f] of usableFiles) {
        byCollection[f.collectionName] ??= {}
        for (const d of f.docs) {
          byCollection[f.collectionName][d.id] = d
        }
      }
      for (const collectionName of COLLECTION_ORDER) {
        const docsById = byCollection[collectionName]
        if (!docsById) continue
        const total = Object.keys(docsById).length
        setProgress((prev) => ({ ...prev, [collectionName]: { done: 0, total } }))
        await writeCollection(collectionName, docsById, (n) =>
          setProgress((prev) => ({ ...prev, [collectionName]: { done: n, total } })),
        )
      }
      setDone(true)
    } catch (err) {
      setRunError(err.message)
    } finally {
      setRunning(false)
    }
  }

  return (
    <div className="mx-auto flex max-w-2xl flex-col gap-4 px-4 py-6">
      <h2 className="text-lg font-semibold">Datenimport (einmalig)</h2>
      <p className="text-sm text-[var(--color-text-muted)]">
        Wähle alle Dateien aus, die du von Claude bekommen hast: <code>accounts.json</code>,{' '}
        <code>categories.json</code>, <code>tags-allocation.json</code>,{' '}
        <code>tags-breakdown-2025.json</code>, <code>tags-breakdown-2026.json</code>,{' '}
        <code>jahresabschluss.json</code>, <code>transactions-2025.json</code>,{' '}
        <code>transactions-2026.json</code>, <code>budgets-2025.json</code>,{' '}
        <code>budgets-2026.json</code>. Du kannst sie alle auf einmal auswählen.
      </p>

      <input
        type="file"
        accept=".json"
        multiple
        disabled={running}
        onChange={(e) => handleFilesSelected(e.target.files)}
        className="rounded-lg border border-[var(--color-border)] bg-[var(--color-surface)] p-2 text-sm"
      />

      {Object.keys(files).length > 0 && (
        <ul className="flex flex-col gap-1 rounded-lg border border-[var(--color-border)] bg-[var(--color-surface)] p-3 text-sm">
          {Object.entries(files).map(([name, f]) => (
            <li key={name} className="flex justify-between gap-2">
              <span>{name}</span>
              {f.error ? (
                <span className="text-[var(--color-alert)]">{f.error}</span>
              ) : (
                <span className="text-[var(--color-text-muted)]">
                  {f.collectionName} · {f.count} Dokumente
                </span>
              )}
            </li>
          ))}
        </ul>
      )}

      <button
        type="button"
        disabled={!hasUsableFiles || running}
        onClick={handleImport}
        className="self-start rounded-lg bg-[var(--color-computed)] px-5 py-2.5 font-medium text-white disabled:opacity-50"
      >
        {running ? 'Importiere…' : 'Import starten'}
      </button>

      {Object.keys(progress).length > 0 && (
        <ul className="flex flex-col gap-1 text-sm">
          {COLLECTION_ORDER.filter((c) => progress[c]).map((c) => (
            <li key={c}>
              {c}: {progress[c].done}/{progress[c].total}
              {progress[c].done === progress[c].total ? ' ✓' : ''}
            </li>
          ))}
        </ul>
      )}

      {runError && <p className="text-sm text-[var(--color-alert)]">Fehler: {runError}</p>}
      {done && !runError && (
        <p className="text-sm font-medium text-[var(--color-income)]">
          Import abgeschlossen. Diesen Bildschirm gibt es nur für diesen einmaligen Import — er
          verschwindet, sobald die echten Screens gebaut sind.
        </p>
      )}
    </div>
  )
}
